server:
  port: 8084

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: notification-db

eureka:
  instance:
      preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/